package travel.travel_community.entity.enums;

public enum FavoriteCountry {
    KOREA, BRAZIL, BOLIVIA, ARGENTINA, CHILE, PERU, INDONESIA,NEW_ZEALAND,
    BHUTAN,
    USA_EAST, USA_WEST, MEXICO, CANADA,
    VIETNAM, JAPAN, CHINA, PHILIPPINES,
    MOROCCO, EGYPT, SAUDI_ARABIA, TURKEY,
    AUSTRALIA, EASTERN_EUROPE, NORTHERN_EUROPE, WESTERN_EUROPE
}
