spring:
  web:
    resources:
      static-locations:
        - classpath:/static/
        - file:C:/Users/maste/Desktop/music/
  datasource:
    url: jdbc:mysql://localhost:3306/travel_community
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  thymeleaf:
    prefix : classpath:/templates/
    suffix : .html
    cache : false
  email:
    authentication:
      email: rmsals8@naver.com
      password: hyu589558!@

kakao:
  javascript:
    key: 9493f4c4214e03608933054df74be1d1
